#! /usr/bin/env bash

# Loop wrapper for rcopy.sh.
# Keep copying a directory every minute. This is useful to progressively back up
# files as they are being generated by a long-running job.

### Configuration: ###

# SRC is the directory to copy, with trailing slash to designate its content.
# DEST is the destination directory, no trailings slash.
# By default, SRC and DEST are read from command-line arguments.
SRC=$1
DEST=$2

### Do not edit after this line. ###

while [ 1 ];
do
    echo "Copying $SRC to $DEST"
    echo "Copy will start in 1 min. Type Ctrl+C to stop."
    sleep 60
    rcopy.sh $SRC $DEST
done

